# Paleta fija exportada del terminal original. No requiere Quickshell.

# The basic colors
foreground #ADAAA5
background #141718
selection_foreground    #141718
selection_background    #E2E6E8

# Cursor colors
cursor #ADAAA5
cursor_text_color       #141718

# URL underline color when hovering with mouse
url_color               #A4CAE1

# Kitty window border colors
active_border_color     #b3cad2
inactive_border_color   #717678
bell_border_color       #E1A9B2

# Tab bar colors
active_tab_foreground   #2D434A
active_tab_background   #b3cad2
inactive_tab_foreground #ADAAA5
inactive_tab_background #717678
tab_bar_background      #141718

# The 16 terminal colors

# black
color0 #141718
color8 #717678

# red
color1 #E1A9B2
color9 #F0D5D8

# green
color2  #9FEFB9
color10 #DBF8E2

# yellow
color3  #F9F0B2
color11 #FAF2C3

# blue
color4  #A4CAE1
color12 #E5EEF5

# magenta
color5  #CDB8DF
color13 #ECE2F2

# cyan
color6  #A6E5E9
color14 #DDF5F7

# white
color7  #ADAAA5
color15 #E2E6E8
